import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Camera, ScanSearch, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = { title: "Our Process", description: "See how KicksHub selects, checks, refreshes and describes every pre-loved pair.", alternates:{canonical:"/about"} };

export default function AboutPage(){return <main className="min-h-screen bg-cream text-ink"><SiteHeader />
  <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8 lg:py-28"><div><p className="eyebrow">The KicksHub way</p><h1 className="section-title">Good shoes deserve another chapter.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink/65">We built KicksHub for people who care more about finding the right pair than peeling the plastic off a new box. Our rack is small by design: individual shoes, chosen for their shape, style, and life left in them.</p><p className="mt-5 max-w-xl leading-7 text-ink/65">Pre-loved means honest signs of wear. It should never mean vague photos or surprise condition. That’s why every listing is tied to the real pair and graded before it reaches the shop.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2.5rem]"><Image src="/editorial/thrifted-sneaker-wall.jpg" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-right" alt="Vintage sneakers selected for the KicksHub rack"/><span className="absolute bottom-5 left-5 rotate-[-2deg] rounded-full bg-cream px-4 py-2 text-xs font-bold uppercase tracking-widest">Selected pair by pair</span></div></section>
  <section className="bg-olive px-4 py-24 text-cream sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow text-sand">From find to front door</p><h2 className="section-title max-w-3xl">A simple process. Clear on purpose.</h2><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] bg-white/15 md:grid-cols-3">{[[ScanSearch,"01","We inspect","Uppers, stitching, insoles, outsoles, shape and wear all get a close look."],[Sparkles,"02","We refresh","Pairs are carefully cleaned and prepared while preserving their authentic character."],[Camera,"03","We show","The listing photos, size and condition notes tell you what you need before buying."]].map(([Icon,n,title,text]:any)=><article key={n} className="bg-[#27372d] p-8"><Icon className="size-7 text-rust"/><span className="mt-16 block text-xs text-cream/35">{n}</span><h3 className="mt-3 font-display text-2xl font-black">{title}</h3><p className="mt-4 text-sm leading-6 text-cream/60">{text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-5xl px-4 py-24 text-center sm:px-6"><p className="eyebrow">Our promise</p><h2 className="section-title">We’ll show the scuff.<br/>And tell you it’s there.</h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-ink/65">Condition is part of a thrifted shoe’s story. We use clear grades—like new, excellent, good, or fair—and encourage you to review every available image. If you want another angle, ask before ordering.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/products" className="cta-primary">Browse the current rack <ArrowRight/></Link><Link href="/contact" className="cta-secondary">Ask about a pair</Link></div></section>
  <SiteFooter /></main>}
